title: iBrotNano
description: Just a blog about the meaning of life, the universe, and everything.
url: "https://ibrotnano.github.io"
baseurl: ""
timezone: Europe/Berlin
lang: de
author: Marcel Melzig

social:
  name: iBrotNano
  links:
    - https://github.com/iBrotNano
    - https://www.linkedin.com/in/marcel-melzig-0aa538ab/

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight

permalink: /:categories/:year/:month/:day/:title/

collections:
  posts:
    output: true

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: ""
    values:
      layout: default

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - docker-compose.yml
  - .gitignore
  - _site
  - ibrotnano.code-workspace
